from __future__ import annotations

import io
from datetime import datetime, timezone
from typing import Any

from app.config import settings

# Keys that are metadata, not content
SKIP_KEYS = {"skill_slug", "generated_at", "tool_name", "tool_input", "raw_text"}


def _get_source(draft_content: dict[str, Any]) -> dict[str, Any]:
    """Return the content fields to render, supporting both old tool_input and new flat format."""
    tool_input = draft_content.get("tool_input")
    if tool_input and isinstance(tool_input, dict):
        return tool_input
    return {k: v for k, v in draft_content.items() if k not in SKIP_KEYS and v}


def _get_title(draft_content: dict[str, Any], source: dict[str, Any]) -> str:
    skill_slug = draft_content.get("skill_slug", "hc-advisory")
    return skill_slug.replace("-", " ").title()


def _get_org_name(source: dict[str, Any], title: str) -> str:
    name = source.get("org_name", "")
    if not name:
        summary = source.get("executive_summary", "")
        name = summary[:50].split(".")[0] if summary else title
    return name or title


def _flatten_value(value: Any) -> str:
    """Flatten any value to a readable string."""
    if isinstance(value, str):
        return value
    if isinstance(value, (int, float, bool)):
        return str(value)
    if isinstance(value, list):
        parts = []
        for item in value:
            if isinstance(item, str):
                parts.append(f"• {item}")
            elif isinstance(item, dict):
                sub = ", ".join(f"{k}: {_flatten_value(v)}" for k, v in list(item.items())[:3])
                parts.append(f"• {sub}")
            else:
                parts.append(f"• {item}")
        return "\n".join(parts)
    if isinstance(value, dict):
        return "\n".join(f"{k.replace('_',' ').title()}: {_flatten_value(v)}" for k, v in value.items())
    return str(value)


# ---------------------------------------------------------------------------
# PDF generation (ReportLab)
# ---------------------------------------------------------------------------

def generate_pdf(draft_content: dict[str, Any], brand_kit: dict[str, Any]) -> bytes:
    """Generate a PDF using ReportLab with proper rendering of the new flat content structure."""
    from reportlab.lib import colors
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
    from reportlab.lib.units import cm
    from reportlab.platypus import (
        HRFlowable, Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle
    )

    def _hex(h: str) -> colors.HexColor:
        return colors.HexColor(h if h.startswith("#") else f"#{h}")

    primary_hex = brand_kit.get("primary_color", "#C9A84C")
    secondary_hex = brand_kit.get("secondary_color", "#E2C87A")
    primary = _hex(primary_hex)
    secondary = _hex(secondary_hex)

    source = _get_source(draft_content)
    title = _get_title(draft_content, source)
    org_name = _get_org_name(source, title)

    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=A4,
        leftMargin=2*cm, rightMargin=2*cm,
        topMargin=2*cm, bottomMargin=2*cm,
    )

    styles = getSampleStyleSheet()
    style_h1 = ParagraphStyle("H1", parent=styles["Heading1"],
        textColor=primary, fontSize=20, spaceAfter=6)
    style_h2 = ParagraphStyle("H2", parent=styles["Heading2"],
        textColor=primary, fontSize=13, spaceBefore=14, spaceAfter=4)
    style_body = ParagraphStyle("Body", parent=styles["Normal"],
        fontSize=10, leading=15, spaceAfter=4)
    style_bullet = ParagraphStyle("Bullet", parent=styles["Normal"],
        fontSize=10, leading=14, leftIndent=12, spaceAfter=2,
        bulletText="•", bulletIndent=4)
    style_meta = ParagraphStyle("Meta", parent=styles["Normal"],
        fontSize=9, textColor=colors.HexColor("#888888"), spaceAfter=16)

    story = []

    # Header
    story.append(Paragraph(f"{org_name}", style_h1))
    story.append(Paragraph(f"{title}", ParagraphStyle("Sub", parent=styles["Normal"],
        fontSize=14, textColor=secondary, spaceAfter=4)))
    story.append(Paragraph(
        f"Generated by Aivora HC · {datetime.now(timezone.utc).strftime('%d %B %Y')}",
        style_meta))
    story.append(HRFlowable(width="100%", thickness=2, color=primary))
    story.append(Spacer(1, 0.4*cm))

    for key, value in source.items():
        if not value:
            continue
        label = key.replace("_", " ").title()
        story.append(Paragraph(label, style_h2))

        if isinstance(value, str):
            for para in value.split("\n"):
                if para.strip():
                    story.append(Paragraph(para.strip(), style_body))
        elif isinstance(value, list):
            if all(isinstance(v, str) for v in value):
                for item in value:
                    story.append(Paragraph(str(item), style_bullet))
            elif all(isinstance(v, dict) for v in value):
                # Table for list of objects — use Paragraph cells so text wraps
                style_th = ParagraphStyle("TH", parent=styles["Normal"],
                    fontSize=8, leading=11, textColor=colors.HexColor("#111111"),
                    fontName="Helvetica-Bold")
                style_td = ParagraphStyle("TD", parent=styles["Normal"],
                    fontSize=8, leading=11, textColor=colors.HexColor("#1A1A1A"),
                    wordWrap="CJK")
                rows_data = []
                if value:
                    headers = list(value[0].keys())
                    rows_data.append([
                        Paragraph(h.replace("_", " ").title(), style_th)
                        for h in headers
                    ])
                    for item in value:
                        row = []
                        for h in headers:
                            cell_text = _flatten_value(item.get(h, ""))
                            row.append(Paragraph(cell_text, style_td))
                        rows_data.append(row)
                if rows_data:
                    col_count = len(rows_data[0])
                    col_width = (A4[0] - 4*cm) / col_count
                    tbl = Table(rows_data, colWidths=[col_width]*col_count,
                                repeatRows=1, splitByRow=True)
                    tbl.setStyle(TableStyle([
                        ("BACKGROUND",    (0, 0), (-1, 0),  primary),
                        ("ROWBACKGROUNDS",(0, 1), (-1, -1), [colors.HexColor("#FFFFFF"), colors.HexColor("#FAFAFA")]),
                        ("GRID",          (0, 0), (-1, -1), 0.5, primary),
                        ("LINEBELOW",     (0, 0), (-1, 0),  1.5, primary),
                        ("VALIGN",        (0, 0), (-1, -1), "TOP"),
                        ("TOPPADDING",    (0, 0), (-1, -1), 5),
                        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
                        ("LEFTPADDING",   (0, 0), (-1, -1), 6),
                        ("RIGHTPADDING",  (0, 0), (-1, -1), 6),
                    ]))
                    story.append(tbl)
            else:
                for item in value:
                    story.append(Paragraph(_flatten_value(item), style_bullet))
        elif isinstance(value, dict):
            for k, v in value.items():
                story.append(Paragraph(
                    f"<b>{k.replace('_', ' ').title()}:</b> {_flatten_value(v)}",
                    style_body))
        else:
            story.append(Paragraph(str(value), style_body))

        story.append(Spacer(1, 0.2*cm))

    # Footer
    story.append(Spacer(1, 0.5*cm))
    story.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#cccccc")))
    story.append(Paragraph(
        f"Confidential · Aivora HC Platform · {datetime.now(timezone.utc).year}",
        ParagraphStyle("Footer", parent=styles["Normal"], fontSize=8,
            textColor=colors.HexColor("#aaaaaa"), spaceBefore=6)))

    doc.build(story)
    return buf.getvalue()


# ---------------------------------------------------------------------------
# PPTX generation
# ---------------------------------------------------------------------------

def generate_pptx(draft_content: dict[str, Any], brand_kit: dict[str, Any]) -> bytes:
    """Generate a PowerPoint from draft content — one slide per section."""
    from pptx import Presentation
    from pptx.dml.color import RGBColor
    from pptx.util import Inches, Pt

    def _rgb(hex_color: str) -> RGBColor:
        h = hex_color.lstrip("#")
        return RGBColor(int(h[0:2], 16), int(h[2:4], 16), int(h[4:6], 16))

    primary_hex = brand_kit.get("primary_color", "#1A1A2E")
    font_name = brand_kit.get("font", "Calibri")

    source = _get_source(draft_content)
    title = _get_title(draft_content, source)
    org_name = _get_org_name(source, title)

    prs = Presentation()
    prs.slide_width = Inches(13.33)
    prs.slide_height = Inches(7.5)

    # --- Title slide ---
    slide = prs.slides.add_slide(prs.slide_layouts[0])
    if slide.shapes.title:
        slide.shapes.title.text = org_name
        slide.shapes.title.text_frame.paragraphs[0].font.size = Pt(36)
        slide.shapes.title.text_frame.paragraphs[0].font.color.rgb = _rgb(primary_hex)
        slide.shapes.title.text_frame.paragraphs[0].font.name = font_name
    if len(slide.placeholders) > 1:
        slide.placeholders[1].text = (
            f"{title} · Generated by Aivora HC · {datetime.now(timezone.utc).strftime('%B %Y')}"
        )

    # --- One content slide per section ---
    for key, value in source.items():
        if not value:
            continue
        label = key.replace("_", " ").title()
        body_text = _flatten_value(value)
        if not body_text.strip():
            continue

        slide = prs.slides.add_slide(prs.slide_layouts[1])
        if slide.shapes.title:
            slide.shapes.title.text = label
            slide.shapes.title.text_frame.paragraphs[0].font.color.rgb = _rgb(primary_hex)
            slide.shapes.title.text_frame.paragraphs[0].font.name = font_name
            slide.shapes.title.text_frame.paragraphs[0].font.size = Pt(24)

        if len(slide.placeholders) > 1:
            tf = slide.placeholders[1].text_frame
            tf.word_wrap = True
            tf.text = body_text[:2500]
            for para in tf.paragraphs:
                para.font.name = font_name
                para.font.size = Pt(13)

    buf = io.BytesIO()
    prs.save(buf)
    return buf.getvalue()


# ---------------------------------------------------------------------------
# DOCX generation
# ---------------------------------------------------------------------------

def generate_docx(draft_content: dict[str, Any], brand_kit: dict[str, Any]) -> bytes:
    """Generate a Word document from draft content."""
    from docx import Document
    from docx.shared import Pt, RGBColor

    def _rgb(hex_color: str) -> RGBColor:
        h = hex_color.lstrip("#")
        return RGBColor(int(h[0:2], 16), int(h[2:4], 16), int(h[4:6], 16))

    primary_color = _rgb(brand_kit.get("primary_color", "#1A1A2E"))
    font_name = brand_kit.get("font", "Calibri")

    source = _get_source(draft_content)
    title = _get_title(draft_content, source)
    org_name = _get_org_name(source, title)

    doc = Document()

    # Title
    title_para = doc.add_heading(level=0)
    run = title_para.add_run(f"{org_name} — {title}")
    run.font.name = font_name
    run.font.color.rgb = primary_color
    run.font.size = Pt(26)

    # Subtitle
    sub = doc.add_paragraph()
    sub_run = sub.add_run(f"Generated by Aivora HC  |  {datetime.now(timezone.utc).strftime('%B %Y')}")
    sub_run.font.size = Pt(11)
    sub_run.font.color.rgb = RGBColor(0x88, 0x88, 0x88)
    doc.add_paragraph()

    for key, value in source.items():
        if not value:
            continue
        label = key.replace("_", " ").title()

        heading = doc.add_heading(label, level=1)
        for run in heading.runs:
            run.font.color.rgb = primary_color
            run.font.name = font_name

        if isinstance(value, str):
            for line in value.split("\n"):
                if line.strip():
                    doc.add_paragraph(line.strip())
        elif isinstance(value, list):
            if all(isinstance(v, str) for v in value):
                for item in value:
                    p = doc.add_paragraph(style="List Bullet")
                    p.add_run(str(item))
            elif all(isinstance(v, dict) for v in value):
                # Table
                if value:
                    headers = list(value[0].keys())
                    table = doc.add_table(rows=1, cols=len(headers))
                    table.style = "Light Grid Accent 1"
                    for i, h in enumerate(headers):
                        table.rows[0].cells[i].text = h.replace("_", " ").title()
                    for item in value:
                        row = table.add_row()
                        for i, h in enumerate(headers):
                            row.cells[i].text = _flatten_value(item.get(h, ""))[:300]
            else:
                for item in value:
                    p = doc.add_paragraph(style="List Bullet")
                    p.add_run(_flatten_value(item))
        elif isinstance(value, dict):
            for k, v in value.items():
                p = doc.add_paragraph()
                run = p.add_run(f"{k.replace('_', ' ').title()}: ")
                run.bold = True
                p.add_run(_flatten_value(v))
        else:
            doc.add_paragraph(str(value))

        doc.add_paragraph()

    # Footer
    footer = doc.add_paragraph("Confidential – Aivora HC Platform")
    footer.runs[0].font.size = Pt(9)
    footer.runs[0].font.color.rgb = RGBColor(0xAA, 0xAA, 0xAA)

    buf = io.BytesIO()
    doc.save(buf)
    return buf.getvalue()
