"""Spec-driven studio reports.

Some studios ship with a client-authored master instruction document (a
"spec") that defines the studio's expert persona, analysis method and the
structure of its deliverable. When a spec exists under ``studio_prompts/``,
the studio's detailed report is generated by the LLM following that spec,
rendered as a StudioOutputDocument. Studios without a spec keep their coded
builders.
"""
from __future__ import annotations

import json
from pathlib import Path
from typing import Any

_PROMPTS_DIR = Path(__file__).parent / "studio_prompts"
_SPEC_CACHE: dict[str, str | None] = {}

_SPEC_META = {
    "mobility": {"studio_id": "ai_advisory:mobility", "studio_name": "Talent Mobility Studio"},
}


def load_spec(slug: str | None) -> str | None:
    """Full master instruction for a studio slug, or None if it has no spec."""
    if not slug:
        return None
    key = slug.strip().lower().replace("_", "-")
    if key not in _SPEC_CACHE:
        path = _PROMPTS_DIR / f"{key}.md"
        _SPEC_CACHE[key] = path.read_text() if path.exists() else None
    return _SPEC_CACHE[key]


# The spec's "Recommended Output Structure" (section 17), mapped onto the
# section layouts StudioRenderer actually renders.
_OUTPUT_CONTRACT = """

=== PLATFORM OUTPUT CONTRACT (overrides any formatting guidance above) ===

You are generating the comprehensive deliverable defined in "Recommended Output Structure" above. Respond with ONLY a JSON object (no markdown fence) shaped as a StudioOutputDocument:

{
  "title": "...",                 // deliverable title including the organization name
  "subtitle": "...",              // one line: deliverable type, organization, scope
  "sections": [ ... ]             // 10 sections, in this exact order
}

Each section: {"id": "...", "title": "...", "layout": "...", "data": {...}, "footnote": "optional"}

THE 10 SECTIONS (implementing the 19-part recommended structure):

1. id "executive_summary", layout "narrative_paragraph"
   data: {"body": "Executive summary (2-3 paragraphs) opening with the advisory interpretation per the Advisory Response Opening rule, followed by what the AI understood about the organization and request.", "highlights": ["key phrase", ...]}

2. id "diagnosis", layout "narrative_paragraph"
   data: {"body": "Current-state diagnosis: the mobility problem types identified, the root causes behind them, written specifically for this organization.", "highlights": [...]}

3. id "evidence", layout "comparison_table"
   data: {"columns": [{"key": "item", "label": "Item"}, {"key": "status", "label": "Status"}, {"key": "detail", "label": "Detail"}],
          "rows": [{"item": "...", "status": "Evidence used | Missing evidence | Assumption", "detail": "..."}]}
   4-8 rows covering evidence used, missing evidence and assumptions honestly.

4. id "maturity", layout "kpi_grid"
   data: {"columns": 3, "items": [
     {"label": "Mobility Maturity", "value": <1-5>, "unit": "/5", "sublabel": "<level name: Ad Hoc|Emerging|Defined|Integrated|AI-Enabled Marketplace> - one-line rationale"},
     {"label": "Evidence Quality", "value": "<Strong|Moderate|Limited|Insufficient>", "sublabel": "why"},
     {"label": "Confidence", "value": "<High|Medium|Low>", "sublabel": "per the confidence calibration rules"}]}
   footnote: fuller rationale for the maturity rating.

5. id "target_state", layout "narrative_paragraph"
   data: {"body": "Recommended target-state model and the framework/solution design: principles, scope, mobility types in scope, employee/manager/HR journeys, matching logic where relevant - tailored to the organization's size and industry per the customization rules.", "highlights": [...]}

6. id "governance_raci", layout "comparison_table"
   data: {"columns": [{"key": "activity", "label": "Activity"}, {"key": "chro", "label": "CHRO"}, {"key": "talent", "label": "Talent Mgmt"}, {"key": "hrbp", "label": "HRBP"}, {"key": "manager", "label": "Manager"}, {"key": "employee", "label": "Employee"}],
          "rows": [{"activity": "...", "chro": "A", "talent": "R", "hrbp": "C", "manager": "R", "employee": "I"}]}
   6-10 governance activities with R/A/C/I values.

7. id "kpis", layout "comparison_table"
   data: {"columns": [{"key": "kpi", "label": "KPI"}, {"key": "family", "label": "Family"}, {"key": "target", "label": "Target"}, {"key": "cadence", "label": "Cadence"}, {"key": "owner", "label": "Owner"}],
          "rows": [...]}
   6-10 KPIs mixing strategic, operational, employee experience, quality/fairness and development families.

8. id "risks", layout "risk_flags_list"
   data: {"items": [{"id": "r1", "severity": "critical|high|medium|low", "title": "...", "description": "...", "mitigation": "..."}]}
   4-6 risks relevant to this organization with concrete mitigations.

9. id "roadmap", layout "timeline"
   data: {"horizons": [{"label": "Quick wins (0-3 months)", "actions": [{"title": "...", "owner": "..."}]}, {"label": "Phase 2 (3-6 months)", "actions": [...]}, {"label": "Long-term (6-12+ months)", "actions": [...]}]}
   Quick wins are the first horizon.

10. id "next_action", layout "callout_quote"
    data: {"quote": "The single specific recommended next action, per the Recommended Next Action Logic (never generic).",
           "attribution": "Confidence: <High|Medium|Low> - one line on why, referencing evidence quality.",
           "role": "Recommended next action", "emphasis": "insight"}

RULES:
- Ground every section in the specific choices the client made in onboarding and the challenge brief (their priorities, flagged challenges and severity, strategic drivers, advisory questions, industry, region, size, uploaded evidence). Name those choices explicitly and build the diagnosis, maturity rating and recommendations directly on them. The executive summary must reflect their stated situation back in their own terms. Never produce generic content that ignores their inputs.
- ONLY the layouts listed above are valid ("narrative_paragraph", "comparison_table", "kpi_grid", "risk_flags_list", "timeline", "callout_quote"). NEVER invent layout names such as "infographic" - when the client asks for an infographic or visual section, express it as a kpi_grid (stat tiles), a comparison_table, or a timeline. Any other layout name will fail to render.
- Ground everything in the client context provided below (brief, onboarding, conversation). Follow the customization rules for their persona, size, industry and region.
- Never claim high confidence when evidence is missing.
- When a figure or benchmark comes from a real, publicly citable source, put the full source URL in that section's "footnote"; a bare URL is rendered to the user as a clickable citation. If a section has no external source, leave the footnote empty - never write "not specified" and never invent a URL.
- Plain hyphens only, never em-dashes or smart quotes.
"""


async def generate_spec_report(
    slug: str,
    *,
    transcript: str = "",
    context_blocks: list[str] | None = None,
    model: str = "gpt-4o",
) -> dict[str, Any]:
    """Generate a spec-driven StudioOutputDocument. Raises on LLM failure."""
    from app.services.ai_orchestrator import _get_client
    from app.services.model_settings import completion_params

    spec = load_spec(slug)
    if spec is None:
        raise LookupError(f"No spec registered for studio {slug!r}")

    system = spec + _OUTPUT_CONTRACT
    if context_blocks:
        system += "\n\n=== CLIENT CONTEXT ===\n\n" + "\n\n".join(b for b in context_blocks if b)

    user_msg = (
        f"WORKING SESSION TRANSCRIPT:\n\n{transcript[:20000]}\n\nGenerate the comprehensive deliverable now."
        if transcript
        else "No conversation transcript - generate the comprehensive deliverable directly from the client context, stating the additional assumptions this forces."
    )

    client = _get_client()
    resp = await client.chat.completions.create(
        model=model,
        messages=[
            {"role": "system", "content": system},
            {"role": "user", "content": user_msg},
        ],
        response_format={"type": "json_object"},
        **completion_params(model, temperature=0.4, max_tokens=5000),
    )
    document = json.loads(resp.choices[0].message.content or "{}")
    if not isinstance(document.get("sections"), list) or not document["sections"]:
        raise ValueError("Spec report came back without sections")

    meta = _SPEC_META.get(slug.strip().lower().replace("_", "-"), {})
    document.setdefault("studio_id", meta.get("studio_id", f"ai_advisory:{slug}"))
    document["studio_name"] = meta.get("studio_name", document.get("studio_name", slug.title()))
    document.setdefault("title", document["studio_name"])
    document.setdefault("subtitle", "")
    for section in document["sections"]:
        if isinstance(section, dict) and not section.get("title"):
            section["title"] = _SECTION_TITLES.get(section.get("id", ""), str(section.get("id", "Section")).replace("_", " ").title())
    return document


_SECTION_TITLES = {
    "executive_summary": "Executive Summary",
    "diagnosis": "Current-State Diagnosis & Root Causes",
    "evidence": "Evidence, Gaps & Assumptions",
    "maturity": "Mobility Maturity Assessment",
    "target_state": "Target-State Model & Framework Design",
    "governance_raci": "Governance & RACI",
    "kpis": "KPIs & Success Measures",
    "risks": "Risks & Mitigations",
    "roadmap": "Implementation Roadmap",
    "next_action": "Recommended Next Action",
}
