"""Spec-driven studio reports.

Some studios ship with a client-authored master instruction document (a
"spec") that defines the studio's expert persona, analysis method and the
structure of its deliverable. When a spec exists under ``studio_prompts/``,
the studio's detailed report is generated by the LLM following that spec,
rendered as a StudioOutputDocument. Studios without a spec keep their coded
builders.
"""
from __future__ import annotations

import json
from pathlib import Path
from typing import Any

_PROMPTS_DIR = Path(__file__).parent / "studio_prompts"
_SPEC_CACHE: dict[str, str | None] = {}

_SPEC_META = {
    "mobility": {"studio_id": "ai_advisory:mobility", "studio_name": "Talent Mobility Studio"},
}


def _norm(slug: str | None) -> str | None:
    return slug.strip().lower().replace("_", "-") if slug else None


def load_spec(slug: str | None) -> str | None:
    """On-disk master instruction for a studio slug (file fallback only).

    The primary source is the admin-editable ``report_spec`` on the skill row -
    resolved by ``resolve_spec``. This function is kept for the synchronous
    file-only fallback and for the cheap "does a spec exist" checks.
    """
    key = _norm(slug)
    if not key:
        return None
    if key not in _SPEC_CACHE:
        path = _PROMPTS_DIR / f"{key}.md"
        _SPEC_CACHE[key] = path.read_text() if path.exists() else None
    return _SPEC_CACHE[key]


def invalidate_spec_cache(slug: str | None = None) -> None:
    """Drop the file-spec cache (all, or one slug) after an admin edit."""
    if slug is None:
        _SPEC_CACHE.clear()
    else:
        _SPEC_CACHE.pop(_norm(slug) or "", None)


async def resolve_spec(db: Any, slug: str | None) -> str | None:
    """The studio's report master instruction, DB-first then file.

    Priority: the admin-editable ``skill_registry.report_spec`` for this slug,
    then the on-disk ``studio_prompts/{slug}.md``. Returns None if the studio has
    no spec at all (caller then uses the generic report contract).
    """
    key = _norm(slug)
    if not key:
        return None
    try:
        from sqlalchemy import select
        from app.models.skill import SkillRegistry

        row = (
            await db.execute(select(SkillRegistry.report_spec).where(SkillRegistry.slug == key))
        ).scalar_one_or_none()
        if row and row.strip():
            return row
    except Exception:  # noqa: BLE001 - never let a DB hiccup block report generation
        pass
    return load_spec(key)


# The spec's "Recommended Output Structure" (section 17), mapped onto the
# section layouts StudioRenderer actually renders.
_OUTPUT_CONTRACT = """
=== PLATFORM OUTPUT CONTRACT (overrides any formatting guidance above) ===

You are generating the comprehensive deliverable defined in the studio instruction above. This must read and look like a top-tier consulting INFOGRAPHIC deck - the analysis is carried by charts, tiles, heatmaps and tables, NOT by paragraphs.

=== VISUAL-FIRST (this is the most important rule) ===
The reader should get the whole story from the VISUALS. Text is a bot smell - minimise it.
- Prose (narrative_paragraph) is allowed in AT MOST 2 sections total: the executive summary and (optionally) the target-state framing. Every OTHER data point MUST be expressed as a visual: kpi_grid, bar_chart, radar_chart, heatmap, comparison_table, timeline, risk_flags_list, or the callout_quote.
- Any time you are about to write a paragraph that lists facts, numbers, options, steps, pros/cons or comparisons - STOP and turn it into a table, a kpi_grid or a chart instead.
- Every visual may carry ONE short caption via "data.narration" (a single plain sentence, <= 20 words) explaining what it shows. That caption REPLACES paragraphs - do not also write prose saying the same thing.
- Prefer 5-8 crisp data points per visual over long lists. Numbers on every tile, bar, cell and row. No walls of text anywhere.

Respond with ONLY a JSON object (no markdown fence) shaped as a StudioOutputDocument:

{
  "title": "...",                 // deliverable title including the organization name
  "subtitle": "...",              // one line: deliverable type, organization, scope
  "sections": [ ... ]             // the mandatory core below, PLUS scope sections - see SIZING
}

Each section: {"id": "...", "title": "...", "layout": "...", "data": {...}, "footnote": "optional"}

Every section must earn its place: real numbers, real axes, real matrix cells. Never emit a chart, grid, heatmap or list with placeholder or zero values.

=== SIZING: MATCH THE DELIVERABLE TO THE ASK (this is critical) ===
The studio instruction above describes a BROAD capability - many scope areas, deliverable types, frameworks, methods and KPI families. It is illustrative, not a fixed template. You MUST size the report to what the user actually asked for:
- NARROW / focused ask (one problem, e.g. "help with critical-role risk"): the mandatory core below (~11-15 sections) is enough. Do not pad.
- BROAD ask (e.g. "build our full workforce plan", "design the whole program", "comprehensive strategy"): go LONG - 20 to 35+ sections. After the mandatory core, ADD one dedicated section for EACH relevant scope area, framework, deliverable component or KPI family the studio instruction covers that bears on the user's request. A full workforce plan, for instance, should carry sections for demand forecasting, supply forecasting, gap analysis, headcount/FTE, skills-based planning, segmentation, critical roles, capacity, productivity, cost, sourcing mix, future/emerging roles, localization, scenarios, and so on - each as its own section with the layout that best fits (a table, a kpi_grid, a bar_chart, a heatmap, a timeline).
- Depth tiers, when present in the context (Basic/Thinking/Expert/Deepthinking), scale this: Basic stays near the core; Deepthinking pushes to the top of the range.
Never collapse a broad, multi-part deliverable into the minimum core. If the instruction defines 20+ scope areas and the user asked for the full deliverable, the report should visibly cover them.

=== EXTRA / EXPANSION SECTIONS ===
Beyond the mandatory core, add as many scope sections as the ask warrants, each: {"id": "<slug>", "title": "<the scope area's name>", "layout": "<best-fit VISUAL layout>", "data": {...}, "footnote": "..."}. Expansion sections must be VISUALS - comparison_table, kpi_grid, bar_chart, heatmap, timeline or radar_chart - NEVER narrative_paragraph (the 2-prose-section cap is hard and covers the whole document). Each carries a short "data.narration" caption instead of prose, and real org-specific numbers.

THE MANDATORY CORE SECTIONS (always present, in this order, exact ids; ADD scope sections after per SIZING - a natural place is right after target_state, before governance):

0. id "hero", layout "hero"  (MANDATORY at-a-glance band, ALWAYS the first section)
   data: {
     "eyebrow": "<deliverable type> - <organization>",
     "headline": "<the single sharpest finding as one bold sentence>",
     "subheadline": "<one line naming the stakes and the recommended direction>",
     "highlights": ["<4-5 concrete metric facts, each a label + number, e.g. '14.2% attrition (vs 11% sector)'>"]
   }
   highlights MUST be concrete numbers, never adjectives. This is the scannable strip an executive reads in five seconds.

1. id "executive_summary", layout "narrative_paragraph"
   data: {
     "body": "Executive summary (2-3 paragraphs) opening with the advisory interpretation per the Advisory Response Opening rule, then what the AI understood about the organization and request, then the headline verdict. Use **bold** on the 3-5 phrases that carry the argument.",
     "highlights": [{"phrase": "<exact substring copied verbatim from body>", "sentiment": "good|warning|bad|neutral"}]
   }
   highlights is a list of OBJECTS; each "phrase" MUST appear verbatim (case-insensitive) inside body or it is dropped. 3-5 highlights.

2. id "diagnosis", layout "comparison_table"  (VISUAL, not prose)
   data: {
     "columns": [{"key": "problem", "label": "Problem"}, {"key": "root_cause", "label": "Root Cause"}, {"key": "impact", "label": "Business Impact", "highlight": true}],
     "rows": [{"problem": "...", "root_cause": "...", "impact": "..."}],
     "narration": "One-line caption on the core diagnosis."
   }
   5-8 rows. Flat dicts keyed by column key; first column is the row label. This replaces the diagnosis paragraph - do NOT write a narrative version of it.

3. id "maturity_radar", layout "radar_chart"
   data: {
     "axes": ["<dimension 1>", "<dimension 2>", ...],   // the spec's own maturity dimensions, in order
     "series": [
       {"name": "This organization", "values": [<n1>, <n2>, ...], "color": "#3b82f6"},
       {"name": "Sector benchmark", "values": [<b1>, <b2>, ...]}
     ],
     "max": 5,
     "showLegend": true
   }
   GOTCHA: each series "values" list length MUST equal "axes" length, positionally aligned to the axes (index i of values maps to axis i). Use the spec's dimension count. Scores 1-5. The benchmark series must be a defensible sector figure, not a copy of the org.
   footnote: full https:// URL for the sector benchmark if it comes from a real citable source, else "".

4. id "evidence", layout "comparison_table"
   data: {
     "columns": [{"key": "item", "label": "Item"}, {"key": "status", "label": "Status"}, {"key": "detail", "label": "Detail"}],
     "rows": [{"item": "...", "status": "Evidence used | Missing evidence | Assumption", "detail": "..."}]
   }
   GOTCHA: rows are FLAT DICTS keyed by column "key"; the first column ("item") is the row label. 4-8 rows covering evidence used, missing evidence and assumptions honestly.

5. id "evidence_kpis", layout "kpi_grid"
   data: {
     "columns": 3,
     "items": [
       {"label": "<headline metric>", "value": <number or string>, "unit": "<%, x, days, $ etc>", "sublabel": "<what it measures + basis>", "icon": "<activity|trending-up|trending-down|users|dollar|target|clock|award|alert|check|gauge|layers|zap|heart>", "delta": {"value": <num>, "direction": "up|down|flat", "sentiment": "good|warning|bad|neutral"}}
     ]
   }
   3-6 headline numbers with REAL values drawn from the client evidence or a citable source. Each item needs label + value; delta is an OBJECT (a bare string delta is silently dropped) - include it only when you have a genuine change/comparison. Put the source URL for externally sourced figures in the footnote.
   footnote: full https:// URL if the headline numbers are externally sourced, else "".

6. id "maturity", layout "kpi_grid"
   data: {
     "columns": 3,
     "items": [
       {"label": "Maturity Level", "value": <1-5>, "unit": "/5", "sublabel": "<level name per the spec's scale> - one-line rationale", "icon": "gauge"},
       {"label": "Evidence Quality", "value": "<Strong|Moderate|Limited|Insufficient>", "sublabel": "why", "icon": "layers"},
       {"label": "Confidence", "value": "<High|Medium|Low>", "sublabel": "per the confidence calibration rules", "icon": "target"}
     ]
   }
   footnote: fuller rationale for the maturity rating.

7. id "maturity_heatmap", layout "heatmap"
   data: {
     "rows": ["<role or type 1>", "<role or type 2>", ...],
     "cols": ["<dimension or group 1>", "<dimension or group 2>", ...],
     "values": [[<0-1>, <0-1>, ...], [<0-1>, <0-1>, ...], ...],
     "valueFormat": "percent",
     "colorScale": "sequential"
   }
   Build the role x dimension (or type x group) matrix the spec defines. GOTCHA: "values" is a rows x cols matrix - outer length == rows.length, each inner array length == cols.length, positionally aligned; missing cells render blank. With "valueFormat":"percent" pass 0-1 values (they are multiplied by 100). Populate every cell with a defensible readiness/coverage score.

8. id "target_state", layout "narrative_paragraph"
   data: {
     "body": "Recommended target-state model and framework/solution design: principles, scope, types in scope, employee/manager/HR journeys, matching or operating logic where relevant - tailored to the organization's size and industry per the customization rules.",
     "highlights": [{"phrase": "<verbatim substring>", "sentiment": "good|warning|bad|neutral"}]
   }
   Immediately followed by section 9, its comparison_table companion.

9. id "target_state_comparison", layout "comparison_table"
   data: {
     "columns": [{"key": "dimension", "label": "Dimension"}, {"key": "current", "label": "Current State"}, {"key": "target", "label": "Target State"}, {"key": "gap", "label": "Gap / Move", "highlight": true}],
     "rows": [{"dimension": "...", "current": "...", "target": "...", "gap": "..."}]
   }
   5-8 rows mapping current vs target per the spec's dimensions. Flat-dict rows keyed by "key"; first column is the row label; "highlight": true stars the Gap column.

10. id "governance_raci", layout "comparison_table"
    data: {
      "columns": [{"key": "activity", "label": "Activity"}, {"key": "chro", "label": "CHRO"}, {"key": "talent", "label": "Talent Mgmt"}, {"key": "hrbp", "label": "HRBP"}, {"key": "manager", "label": "Manager"}, {"key": "employee", "label": "Employee"}],
      "rows": [{"activity": "...", "chro": "A", "talent": "R", "hrbp": "C", "manager": "R", "employee": "I"}]
    }
    6-10 governance activities with R/A/C/I values. Adapt role columns to the roles the spec names if different.

11. id "kpis", layout "comparison_table"
    data: {
      "columns": [{"key": "kpi", "label": "KPI"}, {"key": "family", "label": "Family"}, {"key": "target", "label": "Target"}, {"key": "cadence", "label": "Cadence"}, {"key": "owner", "label": "Owner"}],
      "rows": [{"kpi": "...", "family": "...", "target": "...", "cadence": "...", "owner": "..."}]
    }
    6-10 KPIs mixing strategic, operational, employee experience, quality/fairness and development families. Targets must be concrete numbers.

12. id "risks", layout "risk_flags_list"
    data: {
      "items": [
        {"id": "r1", "severity": "critical|high|medium|low", "title": "...", "description": "...", "likelihood": "rare|possible|likely|certain", "mitigation": "...", "owner": "..."}
      ]
    }
    4-6 risks relevant to this organization, ordered most severe first, each with a concrete mitigation and an owner.

13. id "roadmap", layout "timeline"
    data: {
      "horizons": [
        {"label": "Quick wins (0-3 months)", "actions": [{"title": "...", "owner": "..."}]},
        {"label": "Phase 2 (3-6 months)", "actions": [{"title": "...", "owner": "..."}]},
        {"label": "Long-term (6-12+ months)", "actions": [{"title": "...", "owner": "..."}]}
      ]
    }
    Quick wins are the first horizon (rendered as "now"). Each action has a title and an owner.

14. id "next_action", layout "callout_quote"
    data: {
      "quote": "The single specific recommended next action, per the Recommended Next Action Logic (never generic).",
      "attribution": "Confidence: <High|Medium|Low> - one line on why, referencing evidence quality.",
      "role": "Recommended next action",
      "emphasis": "insight"
    }

RULES:
- Ground every section in the specific choices the client made in onboarding and the challenge brief (their priorities, flagged challenges and severity, strategic drivers, advisory questions, industry, region, size, uploaded evidence). Name those choices explicitly and build the diagnosis, radar scores, heatmap cells, maturity rating and recommendations directly on them. The executive summary must reflect their stated situation back in their own terms. Never produce generic content that ignores their inputs.
- ONLY these layouts are valid ("hero", "hero_stat", "process_strip", "narrative_paragraph", "radar_chart", "comparison_table", "kpi_grid", "bar_chart", "progress_bar_list", "pie_chart", "donut_chart", "heatmap", "risk_flags_list", "timeline", "callout_quote"). bar_chart data: {"items": [{"label": "...", "value": <n>, "sentiment": "good|warning|bad|neutral", "benchmark": <n>}], "max": 100, "valueFormat": "percent"} (5-8 bars, benchmark optional).
- "pie_chart" / "donut_chart" render a real circular chart for a share/composition of a whole (sourcing mix, budget split). data: {"items": [{"label": str, "value": num}], "valueFormat": "percent"}. Use for any "% of a whole" breakdown.
- DASHBOARD ONE-PAGER STYLE: for tracker/status/executive-summary deliverables, open with "hero_stat" (a big headline number + supporting sub-stats) then "progress_bar_list" (a two-column status/stage breakdown with counts), and you MAY close with a "process_strip" (a Collect -> Analyse -> Deliver style flow). "hero_stat" data: {"label": "Total positions", "value": 100, "substats": [{"value": 24, "label": "Joined", "sentiment": "good"}, {"value": 40, "label": "In pipeline", "sentiment": "accent"}]}. "process_strip" data: {"eyebrow": "AI Agent in Action", "steps": [{"title": "Collect", "description": "...", "icon": "collect"}, {"title": "Analyse", "description": "...", "icon": "analyze"}, {"title": "Deliver", "description": "...", "icon": "deliver"}], "closing": "Decisions accelerated."}.
- "progress_bar_list" is a clean two-column dashboard of labelled progress bars with counts - USE IT for any stage/status/pipeline/distribution breakdown (e.g. counts by recruitment stage, by readiness level, by risk tier, headcount by unit). data: {"items": [{"label": "Sourcing", "value": 12, "sentiment": "accent|good|warning|bad|neutral|info"}], "columns": 2, "max": <largest value or total>, "valueFormat": "number"}. 6-12 items; give related items distinct sentiments so the colours read like the reference dashboard. NEVER invent layout names such as "infographic" - when the client asks for an infographic or visual, express it as a kpi_grid (stat tiles), a radar_chart, a heatmap, a comparison_table or a timeline. Any other layout name will fail to render.
- Honour the exact data shapes above. Positional-alignment gotchas are load-bearing: radar_chart series values align to axes by index and must match axes length; heatmap values is a rows x cols matrix; kpi_grid delta and narrative_paragraph highlights are OBJECTS (malformed values are silently ignored); comparison_table rows are flat dicts keyed by column key with the first column as the row label.
- Every mandatory visual (radar_chart, heatmap, evidence_kpis grid, risks list, next_action callout) must appear once and be fully populated with real values - no zeros, no placeholders, no empty cells.
- Never claim high confidence when evidence is missing. Reflect honest confidence in the maturity grid, the radar benchmark, and the next_action attribution.
- CITATIONS ARE MANDATORY. If an "EXTERNAL SOURCES" block is provided in the context (each entry has a FINDING and a real https URL), you MUST use it: weave the sourced facts into the relevant sections AND put that section's supporting URL in its "footnote" field. A bare URL in a footnote renders to the user as a clickable citation. At minimum, the benchmark/comparison, kpi/evidence, and maturity sections that reference any external figure must each carry a footnote URL taken verbatim from the EXTERNAL SOURCES block. Only use URLs that appear in that block - never invent a URL, and never leave every footnote empty when sources were supplied. If a specific section genuinely has no external source, leave only that footnote empty (never write "not specified").
- Plain hyphens only, never em-dashes or smart quotes.
"""


async def generate_spec_report(
    slug: str,
    *,
    transcript: str = "",
    context_blocks: list[str] | None = None,
    model: str = "gpt-4o",
    spec: str | None = None,
) -> dict[str, Any]:
    """Generate a spec-driven StudioOutputDocument. Raises on LLM failure.

    ``spec`` is the studio's master instruction; pass the DB-resolved one when
    available, else it falls back to the on-disk file for this slug.

    ``model`` may be a direct OpenAI id (e.g. "gpt-5.1") or an OpenRouter
    "provider/model" id (e.g. "anthropic/claude-opus-4.1"); the right client is
    resolved automatically.
    """
    from app.services.llm_models import (
        completion_params_for,
        get_llm_client,
        resolve_model,
    )

    if spec is None:
        spec = load_spec(slug)
    if spec is None:
        raise LookupError(f"No spec registered for studio {slug!r}")

    system = spec + _OUTPUT_CONTRACT
    if context_blocks:
        system += "\n\n=== CLIENT CONTEXT ===\n\n" + "\n\n".join(b for b in context_blocks if b)

    user_msg = (
        f"WORKING SESSION TRANSCRIPT:\n\n{transcript[:50000]}\n\nGenerate the comprehensive deliverable now."
        if transcript
        else "No conversation transcript - generate the comprehensive deliverable directly from the client context, stating the additional assumptions this forces."
    )

    model = resolve_model(model)
    client = get_llm_client(model)
    resp = await client.chat.completions.create(
        model=model,
        messages=[
            {"role": "system", "content": system},
            {"role": "user", "content": user_msg},
        ],
        response_format={"type": "json_object"},
        # Headroom for long, broad deliverables (up to ~35 sections). The
        # model still sizes to the ask; this only lifts the ceiling.
        **completion_params_for(model, temperature=0.4, max_tokens=16000),
    )
    document = json.loads(resp.choices[0].message.content or "{}")
    if not isinstance(document.get("sections"), list) or not document["sections"]:
        raise ValueError("Spec report came back without sections")

    meta = _SPEC_META.get(slug.strip().lower().replace("_", "-"), {})
    document.setdefault("studio_id", meta.get("studio_id", f"ai_advisory:{slug}"))
    document["studio_name"] = meta.get("studio_name", document.get("studio_name", slug.title()))
    document.setdefault("title", document["studio_name"])
    document.setdefault("subtitle", "")
    for section in document["sections"]:
        if isinstance(section, dict) and not section.get("title"):
            section["title"] = _SECTION_TITLES.get(section.get("id", ""), str(section.get("id", "Section")).replace("_", " ").title())
    return document


_SECTION_TITLES = {
    "executive_summary": "Executive Summary",
    "diagnosis": "Current-State Diagnosis & Root Causes",
    "maturity_radar": "Maturity Radar vs Sector Benchmark",
    "evidence": "Evidence, Gaps & Assumptions",
    "evidence_kpis": "Headline Metrics",
    "maturity": "Maturity Assessment",
    "maturity_heatmap": "Readiness Heatmap",
    "target_state": "Target-State Model & Framework Design",
    "target_state_comparison": "Current vs Target State",
    "governance_raci": "Governance & RACI",
    "kpis": "KPIs & Success Measures",
    "risks": "Risks & Mitigations",
    "roadmap": "Implementation Roadmap",
    "next_action": "Recommended Next Action",
}
